import { HeroUIProvider } from '@heroui/react';
import { montserrat } from '@/app/ui/fonts';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import "./globals.css";

export const metadata = {
  title: "William Branham en México - La Simiente está Viva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} antialiased`} >
        <HeroUIProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </HeroUIProvider>
      </body>
    </html>
  );
}
